# Default values for litellm
replicaCount: 1

image:
  repository: ghcr.io/berriai/litellm
  pullPolicy: IfNotPresent
  tag: "main-latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 4000
  targetPort: 4000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: litellm.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# LiteLLM specific configuration
litellm:
  # Environment variables
  env: {}
  
  # Master key for LiteLLM (will be read from secret created by External Secrets)
  masterKeySecret:
    name: "litellm-admin-auth"  # This will be created by External Secrets Operator
    key: "master-key"
  
  # Configuration file
  config:
    enabled: true
    # Minimal base configuration - model_list should be in deployment repo
    content: |
      general_settings:
        master_key: os.environ/LITELLM_MASTER_KEY

  # Secrets configuration (references to secrets created by External Secrets Operator)
  secrets:
    - name: "litellm-api-keys"  # Created by External Secrets from Azure Key Vault
      keys:
        - "openai-api-key"
        - "anthropic-api-key"
        - "azure-api-key"
        - "azure-api-base"
        - "google-api-key"
    - name: "litellm-admin-auth"  # Created by External Secrets from Azure Key Vault
      keys:
        - "master-key"
        - "jwt-secret"
