apiVersion: v1
kind: Secret
metadata:
  name: litellm-local-secrets
  namespace: litellm
type: Opaque
stringData:
  master-key: "sk-local-master-key-123"
  openai-api-key: "sk-your-openai-key"  # Ersetze mit echtem Key
  google-api-key: "your-google-key"     # Ersetze mit echtem Key
