apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-enterprise-api-keys
  namespace: litellm
  annotations:
    description: "API keys for various LLM providers (OpenAI, Anthropic, Azure, Google)"
spec:
  encryptedData:
    # Generate these with: echo -n "your-actual-api-key" | kubeseal --raw --from-file=/dev/stdin --name=litellm-enterprise-api-keys --namespace=litellm
    openai-api-key: ""      # Replace: sk-...
    anthropic-api-key: ""   # Replace: sk-ant-...
    azure-api-key: ""       # Replace: your-azure-openai-key
    azure-api-base: ""      # Replace: https://your-resource.openai.azure.com/
    google-api-key: ""      # Replace: your-google-ai-studio-key
  template:
    metadata:
      name: litellm-enterprise-api-keys
      namespace: litellm
    type: Opaque
