apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-enterprise-admin-auth
  namespace: litellm
  annotations:
    description: "Admin authentication credentials for LiteLLM UI and API access"
spec:
  encryptedData:
    # Generate these with: echo -n "your-master-key" | kubeseal --raw --from-file=/dev/stdin --name=litellm-enterprise-admin-auth --namespace=litellm
    master-key: ""          # Replace: your-strong-master-key-for-api-access
    admin-email: ""         # Replace: admin@yourcompany.com
    admin-password: ""      # Replace: your-secure-admin-password
    jwt-secret: ""          # Replace: your-jwt-signing-secret-32-chars-min
  template:
    metadata:
      name: litellm-enterprise-admin-auth
      namespace: litellm
    type: Opaque
