apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ./helm-chart
      sourceRef:
        kind: GitRepository
        name: litellm-repo
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: litellm-config
      namespace: litellm
  values:
    replicaCount: 2
    
    image:
      repository: ghcr.io/berriai/litellm
      tag: "main-latest"
      pullPolicy: Always
    
    service:
      type: ClusterIP
      port: 4000
    
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - host: litellm.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: litellm-tls
          hosts:
            - litellm.example.com
    
    # Enable PostgreSQL with SealedSecrets
    postgresql:
      enabled: true
      auth:
        username: litellm
        database: litellm
        existingSecret: "litellm-db-credentials"
        secretKeys:
          adminPasswordKey: "postgres-password"
          userPasswordKey: "user-password"
      primary:
        persistence:
          enabled: true
          size: 20Gi
    
    litellm:
      # Use SealedSecrets (korrigierte Namen)
      masterKeySecret:
        name: "litellm-enterprise-admin-auth"  # Angepasst an SealedSecret Namen
        key: "master-key"
      
      secrets:
        - name: "litellm-enterprise-api-keys"  # Angepasst an SealedSecret Namen
          keys:
            - "openai-api-key"
            - "anthropic-api-key"
            - "azure-api-key"
            - "azure-api-base"
            - "google-api-key"
        - name: "litellm-enterprise-admin-auth"  # Angepasst an SealedSecret Namen
          keys:
            - "master-key"
            - "jwt-secret"
        - name: "litellm-db-credentials"
          keys:
            - "postgres-password"
            - "user-password"
      
      # Use external ConfigMap
      config:
        enabled: false
    
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70
