apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ./helm-chart
      sourceRef:
        kind: GitRepository
        name: litellm-repo
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: litellm-config
      namespace: litellm
  values:
    replicaCount: 1  # Reduziert für lokales Testing
    
    image:
      repository: ghcr.io/berriai/litellm
      tag: "main-latest"
      pullPolicy: Always
    
    service:
      type: NodePort  # Für lokalen Zugriff
      port: 4000
    
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: litellm.local  # Lokale Domain
          paths:
            - path: /
              pathType: Prefix
    
    # PostgreSQL für lokales Testing
    postgresql:
      enabled: true
      auth:
        username: litellm
        database: litellm
        existingSecret: "litellm-db-credentials"
      primary:
        persistence:
          enabled: true
          size: 5Gi  # Kleiner für lokales Testing
    
    litellm:
      masterKeySecret:
        name: "litellm-admin-auth"
        key: "master-key"
      
      secrets:
        - name: "litellm-api-keys"
          keys:
            - "openai-api-key"
            - "anthropic-api-key"
        - name: "litellm-admin-auth"
          keys:
            - "master-key"
            - "jwt-secret"
        - name: "litellm-db-credentials"
          keys:
            - "postgres-password"
            - "user-password"
      
      config:
        enabled: false
    
    resources:
      limits:
        cpu: 500m    # Reduziert für lokales Testing
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    
    autoscaling:
      enabled: false  # Deaktiviert für lokales Testing
