apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-db-credentials
  namespace: litellm
  annotations:
    description: "PostgreSQL database credentials for LiteLLM"
spec:
  encryptedData:
    # Generate these with: echo -n "your-password" | kubeseal --raw --from-file=/dev/stdin --name=litellm-db-credentials --namespace=litellm
    postgres-password: ""    # Replace: strong-postgres-admin-password
    user-password: ""        # Replace: strong-litellm-user-password
  template:
    metadata:
      name: litellm-db-credentials
      namespace: litellm
    type: Opaque
